ALTER SESSION SET CONTAINER = plsqldb;
ALTER SESSION SET CURRENT_SCHEMA = C##DEBEZIUM;

-- Create Script
CREATE TABLE TPJ_ALARM_FILE (
    PROJ_ALARM_KEY NUMBER NOT NULL 
,   FILE_PATH VARCHAR2(1000) NOT NULL 
,   FILE_NAME VARCHAR2(1000) NOT NULL 
,   INPUT_TIME DATE NOT NULL 
,   USER_KEY NUMBER NOT NULL 
,   PROJ_KEY NUMBER NOT NULL 
,   SITE_KEY NUMBER NOT NULL 
) TABLESPACE TD_TPJ;

CREATE UNIQUE INDEX TPJ_ALARM_FILE_PK ON TPJ_ALARM_FILE(PROJ_ALARM_KEY, FILE_PATH, FILE_NAME) TABLESPACE TX_TPJ;

-- Alter Script
ALTER TABLE TPJ_ALARM_FILE ADD (CONSTRAINT TPJ_ALARM_FILE_PK PRIMARY KEY (PROJ_ALARM_KEY, FILE_PATH, FILE_NAME) USING INDEX TPJ_ALARM_FILE_PK);

-- Comment Script
COMMENT ON TABLE TPJ_ALARM_FILE IS 'CTMS 프로젝트에서 발송한 알람 파일을 관리합니다.<br>';
COMMENT ON COLUMN TPJ_ALARM_FILE.PROJ_ALARM_KEY IS '프로젝트알람키';
COMMENT ON COLUMN TPJ_ALARM_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TPJ_ALARM_FILE.FILE_NAME IS '파일명';
COMMENT ON COLUMN TPJ_ALARM_FILE.INPUT_TIME IS '입력/변경 시간';
COMMENT ON COLUMN TPJ_ALARM_FILE.USER_KEY IS '사용자키';
COMMENT ON COLUMN TPJ_ALARM_FILE.PROJ_KEY IS '프로젝트키';
COMMENT ON COLUMN TPJ_ALARM_FILE.SITE_KEY IS '사이트키';
