ALTER SESSION SET CONTAINER = plsqldb;
ALTER SESSION SET CURRENT_SCHEMA = C##DEBEZIUM;

-- Create Script
CREATE TABLE TPJ_ALARM (
    PROJ_ALARM_KEY NUMBER NOT NULL 
,   MAIL_TYPE VARCHAR2(10) NOT NULL 
,   TITLE VARCHAR2(1000) NOT NULL 
,   SENDER VARCHAR2(100) NOT NULL 
,   SEND_FLAG CHAR(1) NOT NULL 
,   EFFECT_DATE VARCHAR2(10) NOT NULL 
,   EXPIRED_DATE VARCHAR2(10) NOT NULL 
,   DEL_FLAG CHAR(1) NOT NULL 
,   INPUT_TIME DATE NOT NULL 
,   USER_KEY NUMBER NOT NULL 
,   PROJ_KEY NUMBER NOT NULL 
,   SITE_KEY NUMBER NOT NULL 
) TABLESPACE TD_TPJ;

CREATE UNIQUE INDEX TPJ_ALARM_PK ON TPJ_ALARM(PROJ_ALARM_KEY) TABLESPACE TX_TPJ;

-- Alter Script
ALTER TABLE TPJ_ALARM ADD (CONSTRAINT TPJ_ALARM_PK PRIMARY KEY (PROJ_ALARM_KEY) USING INDEX TPJ_ALARM_PK);

-- Comment Script
COMMENT ON TABLE TPJ_ALARM IS 'CTMS 프로젝트에서 발송한 알람을 관리합니다.<br>';
COMMENT ON COLUMN TPJ_ALARM.PROJ_ALARM_KEY IS '프로젝트알람키';
COMMENT ON COLUMN TPJ_ALARM.MAIL_TYPE IS '메일유형(COLUMN_CODE 참조)';
COMMENT ON COLUMN TPJ_ALARM.TITLE IS '제목';
COMMENT ON COLUMN TPJ_ALARM.SENDER IS '송신자';
COMMENT ON COLUMN TPJ_ALARM.SEND_FLAG IS '전송결과 ("P": 전송대기, "S": 성공, "F": 실패)';
COMMENT ON COLUMN TPJ_ALARM.EFFECT_DATE IS '시작일자';
COMMENT ON COLUMN TPJ_ALARM.EXPIRED_DATE IS '종료일자';
COMMENT ON COLUMN TPJ_ALARM.DEL_FLAG IS '삭제 여부 (Y|N)';
COMMENT ON COLUMN TPJ_ALARM.INPUT_TIME IS '입력/변경 시간';
COMMENT ON COLUMN TPJ_ALARM.USER_KEY IS '입력/변경 사용자 Key';
COMMENT ON COLUMN TPJ_ALARM.PROJ_KEY IS '프로젝트키';
COMMENT ON COLUMN TPJ_ALARM.SITE_KEY IS '사이트키';
