ALTER SESSION SET CONTAINER = plsqldb;
ALTER SESSION SET CURRENT_SCHEMA = C##DEBEZIUM;

-- Create Script
CREATE TABLE TPJ_ALARM_CONTENT (
    PROJ_ALARM_KEY NUMBER NOT NULL 
,   CONTENT CLOB NOT NULL 
,   INPUT_TIME DATE NOT NULL 
,   USER_KEY NUMBER NOT NULL 
,   PROJ_KEY NUMBER NOT NULL 
,   SITE_KEY NUMBER NOT NULL 
) TABLESPACE TD_TPJ;

CREATE UNIQUE INDEX TPJ_ALARM_CONTENT_PK ON TPJ_ALARM_CONTENT(PROJ_ALARM_KEY) TABLESPACE TX_TPJ;

-- Alter Script
ALTER TABLE TPJ_ALARM_CONTENT ADD (CONSTRAINT TPJ_ALARM_CONTENT_PK PRIMARY KEY (PROJ_ALARM_KEY) USING INDEX TPJ_ALARM_CONTENT_PK);

-- Comment Script
COMMENT ON TABLE TPJ_ALARM_CONTENT IS 'CTMS 프로젝트에서 발송한 알람 내용을 관리합니다.<br>';
COMMENT ON COLUMN TPJ_ALARM_CONTENT.PROJ_ALARM_KEY IS '프로젝트알람키';
COMMENT ON COLUMN TPJ_ALARM_CONTENT.CONTENT IS '내용';
COMMENT ON COLUMN TPJ_ALARM_CONTENT.INPUT_TIME IS '입력/변경 시간';
COMMENT ON COLUMN TPJ_ALARM_CONTENT.USER_KEY IS '사용자키';
COMMENT ON COLUMN TPJ_ALARM_CONTENT.PROJ_KEY IS '프로젝트키';
COMMENT ON COLUMN TPJ_ALARM_CONTENT.SITE_KEY IS '사이트키';
