ALTER SESSION SET CONTAINER = plsqldb;
ALTER SESSION SET CURRENT_SCHEMA = C##DEBEZIUM;

-- Create Script
CREATE TABLE TPJ_ALARM_RECIPIENT (
    PROJ_ALARM_KEY NUMBER NOT NULL 
,   ADDRESS VARCHAR2(100) NOT NULL 
,   RECP_TYPE VARCHAR2(10) NOT NULL 
,   USER_KEY NUMBER  
,   INPUT_TIME DATE NOT NULL 
,   USER_KEY_UPD NUMBER NOT NULL 
,   PROJ_KEY NUMBER NOT NULL 
,   SITE_KEY NUMBER NOT NULL 
) TABLESPACE TD_TPJ;

CREATE UNIQUE INDEX TPJ_ALARM_RECIPIENT_PK ON TPJ_ALARM_RECIPIENT(PROJ_ALARM_KEY, ADDRESS) TABLESPACE TX_TPJ;

-- Alter Script
ALTER TABLE TPJ_ALARM_RECIPIENT ADD (CONSTRAINT TPJ_ALARM_RECIPIENT_PK PRIMARY KEY (PROJ_ALARM_KEY, ADDRESS) USING INDEX TPJ_ALARM_RECIPIENT_PK);

-- Comment Script
COMMENT ON TABLE TPJ_ALARM_RECIPIENT IS 'CTMS 프로젝트에서 발송한 알람 수신자를 관리합니다.<br>';
COMMENT ON COLUMN TPJ_ALARM_RECIPIENT.PROJ_ALARM_KEY IS '프로젝트알람키';
COMMENT ON COLUMN TPJ_ALARM_RECIPIENT.ADDRESS IS '수신처(이메일, 전화번호 등)';
COMMENT ON COLUMN TPJ_ALARM_RECIPIENT.RECP_TYPE IS '수신타입(TO, CC, BCC…)';
COMMENT ON COLUMN TPJ_ALARM_RECIPIENT.USER_KEY IS '사용자키';
COMMENT ON COLUMN TPJ_ALARM_RECIPIENT.INPUT_TIME IS '입력/변경 시간';
COMMENT ON COLUMN TPJ_ALARM_RECIPIENT.USER_KEY_UPD IS '입력/변경 사용자키';
COMMENT ON COLUMN TPJ_ALARM_RECIPIENT.PROJ_KEY IS '프로젝트키';
COMMENT ON COLUMN TPJ_ALARM_RECIPIENT.SITE_KEY IS '사이트키';
