ALTER SESSION SET CONTAINER = plsqldb;
ALTER SESSION SET CURRENT_SCHEMA = C##DEBEZIUM;

CREATE TABLE TPJ_PROJECT (
    PROJ_KEY NUMBER NOT NULL 
,   SITE_KEY NUMBER NOT NULL 
,   PROJ_ID VARCHAR2(40) NOT NULL 
,   PROTOCOL VARCHAR2(200) NOT NULL 
,   ALIAS VARCHAR2(1000) NOT NULL 
,   PHASE VARCHAR2(10) NOT NULL 
,   PRODUCT VARCHAR2(200) NOT NULL 
,   START_DATE VARCHAR2(10)  
,   END_DATE VARCHAR2(10)  
,   INDICATION VARCHAR2(200)  
,   SITE_NUM NUMBER  
,   SUBJ_NUM NUMBER  
,   SUBJ_PERIORD VARCHAR2(3)  
,   FPI VARCHAR2(10)  
,   LPI VARCHAR2(10)  
,   PAY_UNIT VARCHAR2(10)  
,   STUDY_KEY NUMBER  
,   IS_SYNC VARCHAR2(1)  
,   EFFECT_DATE VARCHAR2(10)  
,   EXPIRED_DATE VARCHAR2(10)  
,   DESCRIPTION VARCHAR2(4000)  
,   REASON VARCHAR2(400) NOT NULL 
,   DEL_FLAG CHAR(1) NOT NULL 
,   INPUT_TIME DATE NOT NULL 
,   USER_KEY NUMBER NOT NULL 
,   SIVR NUMBER  
,   SQVR NUMBER  
,   IMVR NUMBER  
,   COVR NUMBER  
,   OTVR NUMBER  
,   STATUS VARCHAR2(2)  
,   IS_SYNC_SAE VARCHAR2(1)  
,   IS_SYNC_PDPV VARCHAR2(1)  
,   PHASE_OTHER VARCHAR2(200)  
,   PAY_UNIT_OTHER VARCHAR2(200)  
,   APR_HIS_ATTACH VARCHAR2(1)  
,   TITLE VARCHAR2(1000)  
,   IS_SYNC_SITE_ID CHAR(1)  
,   MVR_HIS_ATTACH CHAR(1)  
) TABLESPACE TD_TPJ;

CREATE UNIQUE INDEX TPJ_PROJECT_PK ON TPJ_PROJECT(PROJ_KEY) TABLESPACE TX_TPJ;
CREATE UNIQUE INDEX TPJ_PROJECT_UK01 ON TPJ_PROJECT(SITE_KEY, PROJ_ID) TABLESPACE TX_TPJ;


ALTER TABLE TPJ_PROJECT ADD (CONSTRAINT TPJ_PROJECT_PK PRIMARY KEY (PROJ_KEY) USING INDEX TPJ_PROJECT_PK);

COMMENT ON TABLE TPJ_PROJECT IS '�� Project�� ���� ������ �����Ѵ�.<br>* �� Record�� �������� �ʴ´�.<br>* STUDY_KEY�� CDMS���� Project�� ��� ����, CTMS �ܵ��� ��� NULL�� �����Ѵ�.';
COMMENT ON COLUMN TPJ_PROJECT.PROJ_KEY IS '������Ʈ Ű';
COMMENT ON COLUMN TPJ_PROJECT.SITE_KEY IS '����Ʈ(������) Ű';
COMMENT ON COLUMN TPJ_PROJECT.PROJ_ID IS '������Ʈ ���̵�';
COMMENT ON COLUMN TPJ_PROJECT.PROTOCOL IS '��������';
COMMENT ON COLUMN TPJ_PROJECT.ALIAS IS '��Ī';
COMMENT ON COLUMN TPJ_PROJECT.PHASE IS 'phase';
COMMENT ON COLUMN TPJ_PROJECT.PRODUCT IS 'Investigational Product';
COMMENT ON COLUMN TPJ_PROJECT.START_DATE IS '������';
COMMENT ON COLUMN TPJ_PROJECT.END_DATE IS '�Ϸ���';
COMMENT ON COLUMN TPJ_PROJECT.INDICATION IS 'indication';
COMMENT ON COLUMN TPJ_PROJECT.SITE_NUM IS '�� ����';
COMMENT ON COLUMN TPJ_PROJECT.SUBJ_NUM IS '������ ��';
COMMENT ON COLUMN TPJ_PROJECT.SUBJ_PERIORD IS '����� ������ ����(Weekly, Monthly)';
COMMENT ON COLUMN TPJ_PROJECT.FPI IS 'Target FPI';
COMMENT ON COLUMN TPJ_PROJECT.LPI IS 'Target LPI';
COMMENT ON COLUMN TPJ_PROJECT.PAY_UNIT IS 'ȭ�� ����';
COMMENT ON COLUMN TPJ_PROJECT.STUDY_KEY IS 'cubeCDMS�� ������ ���� Ű';
COMMENT ON COLUMN TPJ_PROJECT.IS_SYNC IS '��������';
COMMENT ON COLUMN TPJ_PROJECT.EFFECT_DATE IS '���� ������';
COMMENT ON COLUMN TPJ_PROJECT.EXPIRED_DATE IS '���� �Ϸ���';
COMMENT ON COLUMN TPJ_PROJECT.DESCRIPTION IS '����';
COMMENT ON COLUMN TPJ_PROJECT.REASON IS '���� ����';
COMMENT ON COLUMN TPJ_PROJECT.DEL_FLAG IS '��������';
COMMENT ON COLUMN TPJ_PROJECT.INPUT_TIME IS '�Է�/������';
COMMENT ON COLUMN TPJ_PROJECT.USER_KEY IS '�Է�/������ �����';
COMMENT ON COLUMN TPJ_PROJECT.SIVR IS 'SIVR ����';
COMMENT ON COLUMN TPJ_PROJECT.SQVR IS 'SQVR ����';
COMMENT ON COLUMN TPJ_PROJECT.IMVR IS 'IMVR ����';
COMMENT ON COLUMN TPJ_PROJECT.COVR IS 'COVR ����';
COMMENT ON COLUMN TPJ_PROJECT.OTVR IS 'OTVR ����';
COMMENT ON COLUMN TPJ_PROJECT.STATUS IS 'Project ���� (N:Not yet recruiting, R:Recruiting, T:Terminated, C:Completed)';
COMMENT ON COLUMN TPJ_PROJECT.IS_SYNC_SAE IS 'SAE ���� ����';
COMMENT ON COLUMN TPJ_PROJECT.IS_SYNC_PDPV IS 'PDPV ���� ����';
COMMENT ON COLUMN TPJ_PROJECT.PHASE_OTHER IS 'PHASE Other�Է�';
COMMENT ON COLUMN TPJ_PROJECT.PAY_UNIT_OTHER IS 'STATUS Other�Է�';
COMMENT ON COLUMN TPJ_PROJECT.APR_HIS_ATTACH IS 'MVR Approval history ÷�� ����';
COMMENT ON COLUMN TPJ_PROJECT.TITLE IS 'Protocol ����';
COMMENT ON COLUMN TPJ_PROJECT.IS_SYNC_SITE_ID IS 'Site ID ���� ����';
COMMENT ON COLUMN TPJ_PROJECT.MVR_HIS_ATTACH IS 'MVR Audit Trail ÷�� ����';

CREATE TABLE TPJ_PROJECT_HIS (
    PROJ_KEY NUMBER NOT NULL 
,   SITE_KEY NUMBER NOT NULL 
,   PROJ_ID VARCHAR2(40) NOT NULL 
,   PROTOCOL VARCHAR2(200) NOT NULL 
,   ALIAS VARCHAR2(1000) NOT NULL 
,   PHASE VARCHAR2(10) NOT NULL 
,   PRODUCT VARCHAR2(200) NOT NULL 
,   START_DATE VARCHAR2(10)  
,   END_DATE VARCHAR2(10)  
,   INDICATION VARCHAR2(200)  
,   SITE_NUM NUMBER  
,   SUBJ_NUM NUMBER  
,   SUBJ_PERIORD VARCHAR2(3)  
,   FPI VARCHAR2(10)  
,   LPI VARCHAR2(10)  
,   PAY_UNIT VARCHAR2(10)  
,   STUDY_KEY NUMBER  
,   IS_SYNC VARCHAR2(1)  
,   EFFECT_DATE VARCHAR2(10)  
,   EXPIRED_DATE VARCHAR2(10)  
,   DESCRIPTION VARCHAR2(4000)  
,   REASON VARCHAR2(400) NOT NULL 
,   DEL_FLAG CHAR(1) NOT NULL 
,   INPUT_TIME DATE NOT NULL 
,   USER_KEY NUMBER NOT NULL 
,   SIVR NUMBER  
,   SQVR NUMBER  
,   IMVR NUMBER  
,   COVR NUMBER  
,   OTVR NUMBER  
,   STATUS VARCHAR2(2)  
,   IS_SYNC_SAE VARCHAR2(1)  
,   IS_SYNC_PDPV VARCHAR2(1)  
,   PHASE_OTHER VARCHAR2(200)  
,   PAY_UNIT_OTHER VARCHAR2(200)  
,   APR_HIS_ATTACH VARCHAR2(1)  
,   TITLE VARCHAR2(1000)  
,   IS_SYNC_SITE_ID CHAR(1)  
,   MVR_HIS_ATTACH CHAR(1)  
) TABLESPACE TD_TPJ;
CREATE UNIQUE INDEX TPJ_PROJECT_HIS_PK ON TPJ_PROJECT_HIS(PROJ_KEY, INPUT_TIME) TABLESPACE TX_TPJ;

ALTER TABLE TPJ_PROJECT_HIS ADD (CONSTRAINT TPJ_PROJECT_HIS_PK PRIMARY KEY (PROJ_KEY, INPUT_TIME) USING INDEX TPJ_PROJECT_HIS_PK);

COMMENT ON TABLE TPJ_PROJECT_HIS IS '�� Project�� ���� ������ �����Ѵ�.<br>* �� Record�� �������� �ʴ´�.<br>* STUDY_KEY�� CDMS���� Project�� ��� ����, CTMS �ܵ��� ��� NULL�� �����Ѵ�.<br>(�̷�)';
COMMENT ON COLUMN TPJ_PROJECT_HIS.PROJ_KEY IS '������Ʈ Ű';
COMMENT ON COLUMN TPJ_PROJECT_HIS.SITE_KEY IS '����Ʈ(������) Ű';
COMMENT ON COLUMN TPJ_PROJECT_HIS.PROJ_ID IS '������Ʈ ���̵�';
COMMENT ON COLUMN TPJ_PROJECT_HIS.PROTOCOL IS '��������';
COMMENT ON COLUMN TPJ_PROJECT_HIS.ALIAS IS '��Ī';
COMMENT ON COLUMN TPJ_PROJECT_HIS.PHASE IS 'phase';
COMMENT ON COLUMN TPJ_PROJECT_HIS.PRODUCT IS 'Investigational Product';
COMMENT ON COLUMN TPJ_PROJECT_HIS.START_DATE IS '������';
COMMENT ON COLUMN TPJ_PROJECT_HIS.END_DATE IS '�Ϸ���';
COMMENT ON COLUMN TPJ_PROJECT_HIS.INDICATION IS 'indication';
COMMENT ON COLUMN TPJ_PROJECT_HIS.SITE_NUM IS '�� ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.SUBJ_NUM IS '������ ��';
COMMENT ON COLUMN TPJ_PROJECT_HIS.SUBJ_PERIORD IS '����� ������ ����(Weekly, Monthly)';
COMMENT ON COLUMN TPJ_PROJECT_HIS.FPI IS 'Target FPI';
COMMENT ON COLUMN TPJ_PROJECT_HIS.LPI IS 'Target LPI';
COMMENT ON COLUMN TPJ_PROJECT_HIS.PAY_UNIT IS 'ȭ�� ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.STUDY_KEY IS 'cubeCDMS�� ������ ���� Ű';
COMMENT ON COLUMN TPJ_PROJECT_HIS.IS_SYNC IS '��������';
COMMENT ON COLUMN TPJ_PROJECT_HIS.EFFECT_DATE IS '���� ������';
COMMENT ON COLUMN TPJ_PROJECT_HIS.EXPIRED_DATE IS '���� �Ϸ���';
COMMENT ON COLUMN TPJ_PROJECT_HIS.DESCRIPTION IS '����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.REASON IS '���� ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.DEL_FLAG IS '��������';
COMMENT ON COLUMN TPJ_PROJECT_HIS.INPUT_TIME IS '�Է�/������';
COMMENT ON COLUMN TPJ_PROJECT_HIS.USER_KEY IS '�Է�/������ �����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.SIVR IS 'SIVR ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.SQVR IS 'SQVR ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.IMVR IS 'IMVR ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.COVR IS 'COVR ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.OTVR IS 'OTVR ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.STATUS IS 'Project ���� (N:Not yet recruiting, R:Recruiting, T:Terminated, C:Completed)';
COMMENT ON COLUMN TPJ_PROJECT_HIS.IS_SYNC_SAE IS 'SAE ���� ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.IS_SYNC_PDPV IS 'PDPV ���� ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.PHASE_OTHER IS 'PHASE Other�Է�';
COMMENT ON COLUMN TPJ_PROJECT_HIS.PAY_UNIT_OTHER IS 'STATUS Other�Է�';
COMMENT ON COLUMN TPJ_PROJECT_HIS.APR_HIS_ATTACH IS 'MVR Approval history ÷�� ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.TITLE IS 'Protocol ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.IS_SYNC_SITE_ID IS 'Site ID ���� ����';
COMMENT ON COLUMN TPJ_PROJECT_HIS.MVR_HIS_ATTACH IS 'MVR Audit Trail ÷�� ����';