ALTER SESSION SET CONTAINER = plsqldb;
ALTER SESSION SET CURRENT_SCHEMA = C##DEBEZIUM;

-- Create Script
CREATE TABLE TPJ_TMF_SYNC_JOB (
    TMF_SYNC_JOB_KEY NUMBER NOT NULL
,   PROJ_KEY NUMBER NOT NULL
,   TMF_SYNC_MVR_TYPE VARCHAR2(200) NOT NULL
,   STATUS CHAR(2) NOT NULL
,   DEL_FLAG CHAR(1) NOT NULL
,   INPUT_TIME DATE NOT NULL
,   USER_KEY NUMBER NOT NULL
,   SITE_KEY NUMBER NOT NULL
) TABLESPACE TD_TPJ;

CREATE UNIQUE INDEX TPJ_TMF_SYNC_JOB_PK ON TPJ_TMF_SYNC_JOB(TMF_SYNC_JOB_KEY) TABLESPACE TX_TPJ;

-- Alter Script
ALTER TABLE TPJ_TMF_SYNC_JOB ADD (CONSTRAINT TPJ_TMF_SYNC_JOB_PK PRIMARY KEY (TMF_SYNC_JOB_KEY) USING INDEX TPJ_TMF_SYNC_JOB_PK);

-- Comment Script
COMMENT ON TABLE TPJ_TMF_SYNC_JOB IS 'CTMS TMF SYNC(MVR 전송) Job 상태를 관리합니다.';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB.TMF_SYNC_JOB_KEY IS 'TMF MVR 전송 배치작업 키';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB.PROJ_KEY IS '프로젝트키';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB.TMF_SYNC_MVR_TYPE IS 'TMF MVR PDF Sync Type(MVR Only, MVR and Letter) ';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB.STATUS IS '상태(R:In Progress, S:Success, F:Fail)';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB.DEL_FLAG IS '삭제 여부 (Y|N)';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB.INPUT_TIME IS '입력/변경 시간';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB.USER_KEY IS '입력/변경 사용자 Key';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB.SITE_KEY IS '고객사 키';


-- Create Script
CREATE TABLE TPJ_TMF_SYNC_JOB_HIS (
    TMF_SYNC_JOB_KEY NUMBER NOT NULL
,   PROJ_KEY NUMBER NOT NULL
,   TMF_SYNC_MVR_TYPE VARCHAR2(200) NOT NULL
,   STATUS CHAR(2) NOT NULL
,   DEL_FLAG CHAR(1) NOT NULL
,   INPUT_TIME DATE NOT NULL
,   USER_KEY NUMBER NOT NULL
,   SITE_KEY NUMBER NOT NULL
) TABLESPACE TD_TPJ;

CREATE UNIQUE INDEX TPJ_TMF_SYNC_JOB_HIS_PK ON TPJ_TMF_SYNC_JOB_HIS(TMF_SYNC_JOB_KEY, INPUT_TIME) TABLESPACE TX_TPJ;

-- Alter Script
ALTER TABLE TPJ_TMF_SYNC_JOB_HIS ADD (CONSTRAINT TPJ_TMF_SYNC_JOB_HIS_PK PRIMARY KEY (TMF_SYNC_JOB_KEY, INPUT_TIME) USING INDEX TPJ_TMF_SYNC_JOB_HIS_PK);

-- Comment Script
COMMENT ON TABLE TPJ_TMF_SYNC_JOB_HIS IS 'CTMS TMF SYNC(MVR 전송) Job 상태를 관리합니다. (이력)';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_HIS.TMF_SYNC_JOB_KEY IS 'TMF MVR 전송 배치작업 키';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_HIS.PROJ_KEY IS '프로젝트키';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_HIS.TMF_SYNC_MVR_TYPE IS 'TMF MVR PDF Sync Type(MVR Only, MVR and Letter) ';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_HIS.STATUS IS '상태(R:In Progress, S:Success, F:Fail)';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_HIS.DEL_FLAG IS '삭제 여부 (Y|N)';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_HIS.INPUT_TIME IS '입력/변경 시간';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_HIS.USER_KEY IS '입력/변경 사용자 Key';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_HIS.SITE_KEY IS '고객사 키';