ALTER SESSION SET CONTAINER = plsqldb;
ALTER SESSION SET CURRENT_SCHEMA = C##DEBEZIUM;

-- Create Script
CREATE TABLE TPJ_TMF_SYNC_JOB_STATUS (
    TMF_SYNC_JOB_KEY NUMBER NOT NULL
,   TSC_KEY NUMBER NOT NULL
,   PROJ_KEY NUMBER NOT NULL
,   TMF_JOB_KEY NUMBER
,   START_TIME DATE NOT NULL
,   END_TIME DATE
,   STATUS CHAR(2) NOT NULL
,   DEL_FLAG CHAR(1) NOT NULL
,   INPUT_TIME DATE NOT NULL
,   USER_KEY NUMBER NOT NULL
,   SITE_KEY NUMBER NOT NULL
) TABLESPACE TD_TPJ;

CREATE UNIQUE INDEX TPJ_TMF_SYNC_JOB_STATUS_PK ON TPJ_TMF_SYNC_JOB_STATUS(TMF_SYNC_JOB_KEY, TSC_KEY) TABLESPACE TX_TPJ;

-- Alter Script
ALTER TABLE TPJ_TMF_SYNC_JOB_STATUS ADD (CONSTRAINT TPJ_TMF_SYNC_JOB_STATUS_PK PRIMARY KEY (TMF_SYNC_JOB_KEY, TSC_KEY) USING INDEX TPJ_TMF_SYNC_JOB_STATUS_PK);

-- Comment Script
COMMENT ON TABLE TPJ_TMF_SYNC_JOB_STATUS IS 'CTMS TMF SYNC(MVR 전송) Job 상태를 관리합니다.<br>';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.TMF_SYNC_JOB_KEY IS 'TMF MVR 전송 배치작업 키';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.TSC_KEY IS 'MVR 스케쥴 키';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.PROJ_KEY IS '프로젝트키';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.TMF_JOB_KEY IS 'TMF에서 응답으로 온 JOB 키';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.START_TIME IS '작업시작일시';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.END_TIME IS '작업종료일시';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.STATUS IS '상태(I:In Progress, S:Success, F:Fail, PF:Partially Failed)';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.DEL_FLAG IS '삭제 여부 (Y|N)';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.INPUT_TIME IS '입력/변경 시간';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.USER_KEY IS '입력/변경 사용자 Key';
COMMENT ON COLUMN TPJ_TMF_SYNC_JOB_STATUS.SITE_KEY IS '고객사 키';
