SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER PLUGGABLE DATABASE ALL OPEN;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

ALTER DATABASE FORCE LOGGING;
ALTER SYSTEM ARCHIVE LOG CURRENT;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_pdbs WHERE pdb_name = 'PLSQLDB';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE plsqldb ADMIN USER pdbadmin IDENTIFIED BY dbz
    FILE_NAME_CONVERT = (''/opt/oracle/oradata/XE/'', ''/opt/oracle/oradata/XE/plsqldb/'')';
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE plsqldb OPEN';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_pdbs WHERE pdb_name = 'JAVADB';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE javadb ADMIN USER pdbadmin IDENTIFIED BY dbz
    FILE_NAME_CONVERT = (''/opt/oracle/oradata/XE/'', ''/opt/oracle/oradata/XE/javadb/'')';
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE javadb OPEN';
    
    -- PLSQLDB 테이블 및 프로시저 등록
    EXECUTE IMMEDIATE 'ALTER SESSION SET CONTAINER = plsqldb';
    EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = C##DEBEZIUM';
    EXECUTE IMMEDIATE '@/opt/oracle/scripts/sql/ddl/TPJ_EMPLOYEE.sql';
    EXECUTE IMMEDIATE '@/opt/oracle/scripts/sql/ddl/TPJ_SALARY.sql';
    EXECUTE IMMEDIATE '@/opt/oracle/scripts/sql/ddl/TPJ_ATTENDANCE.sql';
    EXECUTE IMMEDIATE '@/opt/oracle/scripts/sql/procedure/TPX_EMPLOYEE.sql';
    EXECUTE IMMEDIATE '@/opt/oracle/scripts/sql/procedure/TPX_ATTENDANCE.sql';
    EXECUTE IMMEDIATE '@/opt/oracle/scripts/sql/procedure/TPX_SALARY.sql';
    EXECUTE IMMEDIATE '@/opt/oracle/scripts/sql/procedure/TPX_UPDATE_SALARY.sql';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'C##DEBEZIUM';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER c##debezium IDENTIFIED BY dbz CONTAINER=ALL';
    
    -- 기본 권한
    EXECUTE IMMEDIATE 'GRANT CONNECT, CREATE SESSION, SET CONTAINER TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$DATABASE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT FLASHBACK ANY TABLE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY TABLE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE, EXECUTE_CATALOG_ROLE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY TRANSACTION TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT LOGMINING TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE, LOCK ANY TABLE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO c##debezium CONTAINER=ALL';
    
    -- LOGMNR 관련 권한
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_LOGMNR TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_LOGMNR_D TO c##debezium CONTAINER=ALL';
    
    -- V$ 뷰 접근 권한
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$LOG TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$LOG_HISTORY TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$LOGMNR_LOGS TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$LOGFILE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$ARCHIVED_LOG TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT SELECT ON V_$TRANSACTION TO c##debezium CONTAINER=ALL';
    

    -- QUOTA 설정
    EXECUTE IMMEDIATE 'ALTER USER c##debezium QUOTA UNLIMITED ON SYSTEM';
    EXECUTE IMMEDIATE 'ALTER USER c##debezium QUOTA UNLIMITED ON SYSAUX';
    
    -- 프로시저 생성 권한
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO c##debezium CONTAINER=ALL';
    
    -- 테이블스페이스 관련 권한
    EXECUTE IMMEDIATE 'GRANT CREATE TABLESPACE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT MANAGE TABLESPACE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT ALTER TABLESPACE TO c##debezium CONTAINER=ALL';
    EXECUTE IMMEDIATE 'GRANT DROP TABLESPACE TO c##debezium CONTAINER=ALL';
    
    -- 테이블 삭제 권한
    EXECUTE IMMEDIATE 'GRANT DROP ANY TABLE TO c##debezium CONTAINER=ALL';
  END IF;
END;
/

COMMIT;

EXIT;