SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count 
  FROM DBA_SYS_PRIVS 
  WHERE GRANTEE = 'C##DEBEZIUM' 
  AND PRIVILEGE = 'DROP ANY TABLE';
  
  IF v_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'DROP ANY TABLE privilege not found');
  END IF;
  -- 성공 시 메시지 출력
  DBMS_OUTPUT.PUT_LINE('1');
END;
/

EXIT