ALTER SESSION SET CONTAINER = plsqldb;

CREATE TABLESPACE TD_TPJ
DATAFILE 'td_tpj.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M;

CREATE TABLESPACE TX_TPJ
DATAFILE 'tx_tpj.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M;